stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  image: node:latest
  script:
    - npm install
    - npm run build
    - ls .
  artifacts:
    paths:
      - ./public/
    
  # tags:
  #   - docker

#   artifacts: paths:
#       - node_modules/

deploy to docker hub:
  image: docker:19.03.1
  stage: deploy
  script: 
    - ls .
    - echo $PASSWORD | docker login registry.gitlab.com --username $USERNAME --password-stdin 
    - docker build -t registry.gitlab.com/ingram_lan/freewriting .
    - docker push registry.gitlab.com/ingram_lan/freewriting