stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  image: node:latest
  script:
    - npm install
    - npm run build
    
  # tags:
  #   - docker

#   artifacts: paths:
#       - node_modules/

deploy to docker hub:
  image: docker:latest
  stage: deploy
  script: 
    - docker login registry.gitlab.com -u $USERNAME -p $PASSWORD
    - docker build -t registry.gitlab.com/ingram_lan/freewriting .
    - docker push registry.gitlab.com/ingram_lan/freewriting