image: node:latest

stages:
  - build

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
    - npm run build
  # tags:
  #   - docker

#   artifacts: paths:
#       - node_modules/

# testing_testing:
#   stage: test
#   script: npm test