image: node:latest

stages:
  - build

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
    - npm run build
    - docker login registry.gitlab.com -u $USERNAME -p $PASSWORD
    - docker build -t registry.gitlab.com/ingram_lan/freewriting .
    - docker push registry.gitlab.com/ingram_lan/freewriting
  # tags:
  #   - docker

#   artifacts: paths:
#       - node_modules/

# testing_testing:
#   stage: test
#   script: npm test