# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - run: npm rebuild node-sass

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test

      # run build
      - run: npm run build

      - persist_to_workspace:
          root: .
          paths:
            - ./*
      - run: echo "====================构建完毕=============================="

  deploy:
    machine:
      timezone:
        Asia/Shanghai # 设置上海时区
      enabled: true
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ad:94:f2:7e:1c:d3:dd:06:e9:ba:61:6c:0f:75:df:6e"

      - run: echo "====================部署开始=============================="
      - attach_workspace:
          at: ~/repo
      - run: echo 'export REMOTE_HOST="$REMOTE_HOST"' >> $BASH_ENV
      - run: echo 'export REMOTE_NAME="$REMOTE_NAME"' >> $BASH_ENV
      - run: source $BASH_ENV
      - run: pwd && ls -al
      - run: pwd && ls ./build
      - run: sudo apt-get install sshpass
      - run: ssh-add -l
      - run: sudo sshpass -p $PWD scp -r -o "StrictHostKeyChecking=no"  ./build/ $REMOTE_NAME@$REMOTE_HOST:/root/test/
      - run: echo "====================部署完毕=============================="

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
