version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/gatsby-site
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Fallback cache to be used
            - v1-npm-deps-
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Gatsby Build
          command: npm run build
      - run: docker login repo.treescale.com --username $DOCKER_USER --password $DOCKER_PASS

      # build the application image
      - run: docker build -t $DOCKER_USER/freewriting .

      # deploy the image
      - run: docker push repo.treescale.com/$DOCKER_USER/freewriting:latest
